language: julia
os:
  - osx
  - linux
julia:
  - 0.5
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd());'
#  - julia -e 'ENV["MADS_NO_PYTHON"]=""; ENV["MADS_NO_PLOT"]=""; Pkg.build("Mads"); Pkg.test("Mads"; coverage=true)'
  - julia -e 'Pkg.build("DocumentFunction"); Pkg.test("DocumentFunction"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("DocumentFunction")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'