name = "DocumentFunction"
uuid = "e1f3b4f0-2dc4-57d3-83f7-d4b7faf3b05b"
authors = ["Velimir (monty) Vesselinov"]
version = "0.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
